using System.ComponentModel;
using System.Text.Json.Serialization;

namespace Demo.Orchestrations.SequentialHybrid.Models;

/// <summary>
/// Structured payload produced by the on-device inbox-picker agent. Only
/// the SENDER side is asked of the model — the recipient is always the
/// inbox owner and is read from <c>InboxService</c> in the executor, never
/// generated by the LLM. That removes a whole class of swap errors a small
/// on-device model would otherwise make on two adjacent name-shaped fields.
///
/// Field order is deliberate: the email comes BEFORE the name so the
/// constrained decoder has a strong lexical anchor (the email's domain /
/// local-part) committed before it has to generate the name-shaped string.
///
/// Stored in workflow state by the cloud-prompt adapter; read back by the
/// final-email assembler at the end of the workflow.
/// </summary>
[Description("The single inbox email the user wants to reply to, copied verbatim from the chosen inbox entry.")]
public sealed record PickedEmail(
    [property: Description("Copy verbatim from SENDER_EMAIL in the chosen inbox entry.")]
    string SenderEmail,

    [property: Description("Copy verbatim from SENDER_NAME in the chosen inbox entry.")]
    string SenderName,

    [property: Description("Copy verbatim from SUBJECT in the chosen inbox entry.")]
    string Subject,

    [property: Description("Copy the body of the chosen inbox entry character-for-character. Preserve every paragraph, date, dollar amount, and named person.")]
    string Body)
{
    /// <summary>First-name view of the sender, used for greetings + cloud prompts.</summary>
    [JsonIgnore]
    public string SenderFirstName => FirstNameFrom(SenderName, SenderEmail);

    private static string FirstNameFrom(string? fullName, string? email) =>
        fullName?.Split(' ', 2, StringSplitOptions.RemoveEmptyEntries).FirstOrDefault()
        ?? email?.Split('@').FirstOrDefault()
        ?? "<unknown>";
}
